export interface Subject {
  id: string
  name: string
  color: string
  lessonCount: number
  nextExam: string | null
  icon: string
}

export interface Lesson {
  id: string
  subjectId: string
  topicId?: string
  date: string
  topic: string
  duration: number
  hasNotes: boolean
}

export interface HalfYear {
  id: string
  name: string
  period: string
  isCurrent: boolean
}

export interface Topic {
  id: string
  subjectId: string
  halfYearId: string
  name: string
  kcAligned: boolean
  lessonIds: string[]
}

export interface SmartNote {
  id: string
  lessonId: string
  summary: string
  keywords: string[]
  examTopics: string[]
}

export interface FlashCard {
  id: string
  subjectId: string
  noteId?: string
  front: string
  back: string
  keywords?: string[]
  createdAt?: string
}

export interface ExamQuestion {
  id: string
  subjectId: string
  text: string
  points: number
  operator: string
}

export interface ExamResult {
  questionId: string
  userAnswer: string
  score: number
  maxScore: number
  grade: string
  strengths: string[]
  weaknesses: string[]
  suggestion: string
}

export interface UserFolder {
  id: string
  subjectId: string
  halfYearId?: string
  parentFolderId?: string
  name: string
  createdAt: string
  isAutoGenerated?: boolean
}

export interface HomeworkItem {
  id?: string
  subjectId?: string
  description: string
  dueDate?: string
  aiHelp?: string
}

export interface UserNote {
  id: string
  subjectId?: string
  folderId?: string
  title: string
  content: string
  attachments?: string[]
  pdfAttachments?: { name: string }[]
  homeworkItems?: HomeworkItem[]
  qa?: { q: string; a: string }[]
  createdAt: string
}

export interface StundenplanSlot {
  id: string
  day: number // 0=Mo, 1=Di, 2=Mi, 3=Do, 4=Fr
  startTime: string // "08:00"
  endTime: string   // "08:45"
  subjectId: string
  room?: string
}

export interface Stundenplan {
  slots: StundenplanSlot[]
  createdAt: string
}

export interface AbiGradeEntry {
  subjectId: string
  schriftlich: number | null
  muendlich: number | null
  schriftlichGrades?: (number | null)[]  // multiple grades; avg used for S/M calculation
  muendlichGrades?: (number | null)[]    // multiple grades; avg used for S/M calculation
  isLK: boolean
  smRatio?: number           // schriftlich share: 0.5 = 50/50, 0.6 = 60/40 … default 0.5
  endnoteOverride?: number | null  // manual override of the rounded Endnote (1–15)
}

export interface AbiHalbjahr {
  id: string
  label: string    // e.g. "Q1", "Q2", "Q3", "Q4"
  entries: AbiGradeEntry[]
}

/* ─── Probeklausur ───────────────────────────────────────────── */

export interface ProbeklausurMaterial {
  id: string           // 'M1', 'M2', 'M3'
  title: string
  type: 'tabelle' | 'diagramm' | 'versuchsaufbau' | 'text' | 'sequenz'
  content: string
}

export interface ProbeklausurTask {
  id: string           // 't1', 't2', etc.
  label: string        // '1', '1.1', 'A1', etc.
  afb: 'I' | 'II' | 'III'
  operator: string
  text: string         // Full task sentence including BE
  be: number
  materialRefs: string[]
}

export interface GeneratedExam {
  subject: string
  subjectId: string
  topic: string
  mode: 1 | 2 | 3 | 4
  materials: ProbeklausurMaterial[]
  tasks: ProbeklausurTask[]
  totalBE: number
}

export interface TaskCorrection {
  taskId: string
  errors: string[]
  gaps: string[]
  formulationHelp: string[]
  scoreNP: number      // 0–15
  justification: string
}

export interface ExamCorrection {
  taskCorrections: TaskCorrection[]
  totalNP: number
  gradeLabel: string   // 'Sehr gut', 'Gut', etc.
  overallJustification: string
}

/* ─── App Statistics ────────────────────────────────────────── */

export interface ExamScoreRecord {
  id: string
  date: string            // ISO date string
  subjectId: string
  gradeLabel: string      // e.g. 'Sehr gut', '1+'
  totalNP: number         // 0–15 Notenpunkte
  source: 'probeklausur' | 'exam'
}

export interface AppStats {
  scanCount: number
  examCount: number
  streak: number
  lastStudyDate: string | null  // 'YYYY-MM-DD'
  studiedDays: string[]         // 'YYYY-MM-DD', last 90 days max
  examScores: ExamScoreRecord[]
}

/* ─── SmartNote (generated) ─────────────────────────────────── */

export interface GeneratedSmartNote {
  lessonId: string
  rawText: string
  contentType?: 'info' | 'aufgabe' | 'beides'
  summary: string
  keywords: string[]
  examTopics: string[]
  solution?: { steps: string[]; answer: string; proof?: string }
  tasks?: Array<{ question: string; steps: string[]; answer: string; proof?: string }>
  generatedAt: string
  subjectName: string
}
