import { createContext, useContext, useState } from 'react'
import { type ReactNode } from 'react'
import type { GeneratedSmartNote, UserFolder, UserNote } from '../types'
import { subjects, topics, halfYears } from '../data/mockData'

export type EntryType = 'lerneinheit' | 'termin' | 'erinnerung'

export interface PersonalEntry {
  id: string
  title: string
  type: EntryType
  date: string
  time: string
}

export interface UserProfile {
  name: string
  klasse: string
  schulform: string
  bundesland: string
  bundeslandId: string
  faecher: string[]
  klausurtermine: { subjectId: string; date: string }[]
  zielnote?: string
}

export type AppTheme = 'light' | 'dark' | 'system'

interface StorageData {
  profile?: UserProfile
  personalEntries?: PersonalEntry[]
  generatedNotes?: Record<string, GeneratedSmartNote>
  userNotes?: UserNote[]
  userFolders?: UserFolder[]
  theme?: AppTheme
}

interface UserContextValue {
  profile: UserProfile | null
  isOnboarded: boolean
  personalEntries: PersonalEntry[]
  generatedNotes: Record<string, GeneratedSmartNote>
  userNotes: UserNote[]
  userFolders: UserFolder[]
  theme: AppTheme
  setTheme: (t: AppTheme) => void
  completeOnboarding: (profile: UserProfile, prebuiltFolders?: UserFolder[]) => void
  updateProfile: (data: Partial<UserProfile>) => void
  addEntry: (entry: PersonalEntry) => void
  removeEntry: (id: string) => void
  saveGeneratedNote: (lessonId: string, note: GeneratedSmartNote) => void
  addUserNote: (note: UserNote) => void
  saveNote: (note: UserNote, generated?: GeneratedSmartNote) => void
  updateUserNote: (note: UserNote) => void
  addFolder: (folder: UserFolder) => void
  deleteFolder: (folderId: string) => void
  saveToOhneFachFolder: (note: UserNote, generated?: GeneratedSmartNote) => void
}

const STORAGE_KEY = 'lernapp_v1'

function loadStorage(): StorageData {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    return raw ? (JSON.parse(raw) as StorageData) : {}
  } catch {
    return {}
  }
}

function saveStorage(data: StorageData) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data))
  } catch {}
}

function halfYearGrade(halfYearId: string): number {
  const m = /kl(\d+)/.exec(halfYearId)
  return m ? parseInt(m[1], 10) : 99
}

// Normal users: 2 simple Halbjahr folders per subject, current year only
function generateDefaultFolders(profile: UserProfile): UserFolder[] {
  const folders: UserFolder[] = []
  const now = new Date().toISOString()
  const klasse = parseInt(profile.klasse, 10)

  for (const subjectId of profile.faecher) {
    folders.push(
      {
        id: `folder-${subjectId}-kl${klasse}-hj1`,
        subjectId,
        halfYearId: `kl${klasse}-hj1`,
        name: `${klasse}. Klasse — 1. Halbjahr`,
        createdAt: now,
        isAutoGenerated: true,
      },
      {
        id: `folder-${subjectId}-kl${klasse}-hj2`,
        subjectId,
        halfYearId: `kl${klasse}-hj2`,
        name: `${klasse}. Klasse — 2. Halbjahr`,
        createdAt: now,
        isAutoGenerated: true,
      },
    )
  }
  return folders
}

// DEV/demo only: KC-topic-aligned folders across all eligible grades
export function generateKcFolders(profile: UserProfile): UserFolder[] {
  const folders: UserFolder[] = []
  const now = new Date().toISOString()
  const maxGrade = parseInt(profile.klasse, 10)

  for (const subjectId of profile.faecher) {
    const subjectTopics = topics.filter(
      (t) => t.subjectId === subjectId && halfYearGrade(t.halfYearId) <= maxGrade,
    )

    if (subjectTopics.length > 0) {
      for (const topic of subjectTopics) {
        folders.push({
          id: `folder-kc-${topic.id}`,
          subjectId,
          halfYearId: topic.halfYearId,
          name: topic.name,
          createdAt: now,
          isAutoGenerated: true,
        })
      }
    } else {
      const subject = subjects.find((s) => s.id === subjectId)
      const currentHalfYear = halfYears.find((h) => h.isCurrent)
      folders.push({
        id: `folder-default-${subjectId}`,
        subjectId,
        halfYearId: currentHalfYear?.id ?? `kl${maxGrade}-hj2`,
        name: `${subject?.name ?? subjectId} — ${profile.klasse}. Klasse`,
        createdAt: now,
        isAutoGenerated: true,
      })
    }
  }
  return folders
}

const UserContext = createContext<UserContextValue | null>(null)

export function UserProvider({ children }: { children: ReactNode }) {
  const stored = loadStorage()

  const [profile, setProfile] = useState<UserProfile | null>(stored.profile ?? null)
  const [theme, setThemeState] = useState<AppTheme>(stored.theme ?? 'dark')
  const [personalEntries, setPersonalEntries] = useState<PersonalEntry[]>(stored.personalEntries ?? [])
  const [generatedNotes, setGeneratedNotes] = useState<Record<string, GeneratedSmartNote>>(
    stored.generatedNotes ?? {},
  )
  const [userNotes, setUserNotes] = useState<UserNote[]>(stored.userNotes ?? [])
  const [userFolders, setUserFolders] = useState<UserFolder[]>(() => {
    if (stored.userFolders && stored.userFolders.length > 0) return stored.userFolders
    if (stored.profile) {
      const generated = generateDefaultFolders(stored.profile)
      saveStorage({ ...stored, userFolders: generated })
      return generated
    }
    return []
  })

  const persist = (
    p: UserProfile | null,
    e: PersonalEntry[],
    n: Record<string, GeneratedSmartNote>,
    un: UserNote[],
    uf: UserFolder[],
    t?: AppTheme,
  ) => saveStorage({ profile: p ?? undefined, personalEntries: e, generatedNotes: n, userNotes: un, userFolders: uf, theme: t ?? theme })

  const setTheme = (t: AppTheme) => {
    setThemeState(t)
    persist(profile, personalEntries, generatedNotes, userNotes, userFolders, t)
  }

  const completeOnboarding = (p: UserProfile, prebuiltFolders?: UserFolder[]) => {
    const folders = prebuiltFolders ?? generateDefaultFolders(p)
    setProfile(p)
    setUserFolders(folders)
    persist(p, personalEntries, generatedNotes, userNotes, folders)
  }

  const updateProfile = (data: Partial<UserProfile>) => {
    if (!profile) return
    const updated = { ...profile, ...data }
    setProfile(updated)
    persist(updated, personalEntries, generatedNotes, userNotes, userFolders)
  }

  const addEntry = (entry: PersonalEntry) => {
    const updated = [...personalEntries, entry]
    setPersonalEntries(updated)
    persist(profile, updated, generatedNotes, userNotes, userFolders)
  }

  const removeEntry = (id: string) => {
    const updated = personalEntries.filter((e) => e.id !== id)
    setPersonalEntries(updated)
    persist(profile, updated, generatedNotes, userNotes, userFolders)
  }

  const saveGeneratedNote = (lessonId: string, note: GeneratedSmartNote) => {
    const updated = { ...generatedNotes, [lessonId]: note }
    setGeneratedNotes(updated)
    persist(profile, personalEntries, updated, userNotes, userFolders)
  }

  const addUserNote = (note: UserNote) => {
    const updated = [...userNotes, note]
    setUserNotes(updated)
    persist(profile, personalEntries, generatedNotes, updated, userFolders)
  }

  const saveNote = (note: UserNote, generated?: GeneratedSmartNote) => {
    const updatedNotes = [...userNotes, note]
    const updatedGenerated = generated
      ? { ...generatedNotes, [note.id]: generated }
      : generatedNotes
    setUserNotes(updatedNotes)
    if (generated) setGeneratedNotes(updatedGenerated)
    persist(profile, personalEntries, updatedGenerated, updatedNotes, userFolders)
  }

  const updateUserNote = (note: UserNote) => {
    const updated = userNotes.map((n) => (n.id === note.id ? note : n))
    setUserNotes(updated)
    persist(profile, personalEntries, generatedNotes, updated, userFolders)
  }

  const addFolder = (folder: UserFolder) => {
    const updated = [...userFolders, folder]
    setUserFolders(updated)
    persist(profile, personalEntries, generatedNotes, userNotes, updated)
  }

  const saveToOhneFachFolder = (note: UserNote, generated?: GeneratedSmartNote) => {
    const folderExists = userFolders.some((f) => f.id === 'folder-no-subject')
    const updatedFolders = folderExists
      ? userFolders
      : [...userFolders, {
          id: 'folder-no-subject',
          subjectId: 'ohne-fach',
          name: 'Schnellnotizen',
          createdAt: new Date().toISOString(),
        }]
    const updatedNotes = [...userNotes, note]
    const updatedGenerated = generated
      ? { ...generatedNotes, [note.id]: generated }
      : generatedNotes
    if (!folderExists) setUserFolders(updatedFolders)
    setUserNotes(updatedNotes)
    if (generated) setGeneratedNotes(updatedGenerated)
    persist(profile, personalEntries, updatedGenerated, updatedNotes, updatedFolders)
  }

  const deleteFolder = (folderId: string) => {
    const updatedFolders = userFolders.filter((f) => f.id !== folderId && f.parentFolderId !== folderId)
    const updatedNotes = userNotes.filter((n) => n.folderId !== folderId)
    setUserFolders(updatedFolders)
    setUserNotes(updatedNotes)
    persist(profile, personalEntries, generatedNotes, updatedNotes, updatedFolders)
  }

  return (
    <UserContext.Provider
      value={{
        profile,
        isOnboarded: profile !== null,
        personalEntries,
        generatedNotes,
        userNotes,
        userFolders,
        theme,
        setTheme,
        completeOnboarding,
        updateProfile,
        addEntry,
        removeEntry,
        saveGeneratedNote,
        addUserNote,
        saveNote,
        updateUserNote,
        addFolder,
        deleteFolder,
        saveToOhneFachFolder,
      }}
    >
      {children}
    </UserContext.Provider>
  )
}

export function useUser() {
  const ctx = useContext(UserContext)
  if (!ctx) throw new Error('useUser must be within UserProvider')
  return ctx
}
